# Practical 10

**Aim:** Demonstrate NumPy array creation, indexing, slicing, reshaping, broadcasting and mathematical operations on multidimensional arrays.

### 1. Array Creation

In [1]:
import numpy as np

v1 = np.array([2.5, 3.5, 4.5, 5.5])
v2 = np.array([[10, 20], [30, 40], [50, 60]])

print("v1:", v1)
print("v2:\n", v2)

print("Zeros:\n", np.zeros((3, 2)))
print("Ones:\n", np.ones((2, 2)))
print("Arange:", np.arange(5, 50, 10))
print("Linspace:", np.linspace(10, 20, 6))
print("Diagonal Identity:\n", np.eye(3))

v1: [2.5 3.5 4.5 5.5]
v2:
 [[10 20]
 [30 40]
 [50 60]]
Zeros:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]]
Arange: [ 5 15 25 35 45]
Linspace: [10. 12. 14. 16. 18. 20.]
Diagonal Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 2. Indexing and Slicing

In [2]:
scores = np.array([75, 82, 90, 65, 88, 92, 70])
print("Element 3:", scores[3])
print("From index 3 onwards:", scores[3:])
print("First 4 elements:", scores[:4])

mat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("\nMatrix:\n", mat)
print("Value at (2, 3):", mat[2, 3])
print("Rows 0 to 1, Cols 2 to 3:\n", mat[0:2, 2:4])
print("Second Column:", mat[:, 1])

Element 3: 65
From index 3 onwards: [65 88 92 70]
First 4 elements: [75 82 90 65]

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Value at (2, 3): 12
Rows 0 to 1, Cols 2 to 3:
 [[3 4]
 [7 8]]
Second Column: [ 2  6 10]


### 3. Reshape and Flatten

In [3]:
seq = np.arange(100, 112)
print("Original:", seq)

mat_2x6 = seq.reshape(2, 6)
print("2x6 Shape:\n", mat_2x6)

print("Flattened back:", mat_2x6.flatten())

Original: [100 101 102 103 104 105 106 107 108 109 110 111]
2x6 Shape:
 [[100 101 102 103 104 105]
 [106 107 108 109 110 111]]
Flattened back: [100 101 102 103 104 105 106 107 108 109 110 111]


### 4. Broadcasting Concept

In [4]:
base = np.array([[10, 20, 30], [40, 50, 60]])
add_val = np.array([5, 10, 15])

print("Base Matrix:\n", base)
print("Vector:", add_val)
print("Result (Base + Vector):\n", base + add_val)
print("Scalar Subtraction (Base - 5):\n", base - 5)

Base Matrix:
 [[10 20 30]
 [40 50 60]]
Vector: [ 5 10 15]
Result (Base + Vector):
 [[15 30 45]
 [45 60 75]]
Scalar Subtraction (Base - 5):
 [[ 5 15 25]
 [35 45 55]]


### 5. Mathematical & Statistical Methods

In [5]:
p = np.array([[3, 5], [1, 2]])
q = np.array([[2, 0], [1, 4]])

print("p + q:\n", p + q)
print("p * q:\n", p * q)
print("Dot product:\n", np.dot(p, q))

print("Sum of all:", p.sum())
print("Min in columns:", p.min(axis=0))
print("Max in rows:", p.max(axis=1))
print("Mean:", p.mean())
print("Std Dev:", round(p.std(), 2))

p + q:
 [[5 5]
 [2 6]]
p * q:
 [[6 0]
 [1 8]]
Dot product:
 [[11 20]
 [ 4  8]]
Sum of all: 11
Min in columns: [1 2]
Max in rows: [5 2]
Mean: 2.75
Std Dev: 1.48
